# Numpy
- Verctoriazation
- Numerical Funtions

In [33]:
#imports the numpy library
import numpy as np

# create a simple numpy arrary
v = np.array([1,2,3])

In [31]:
v.dtype
# v.ndim
# v.size
type(v)

dtype('int64')

In [17]:
m = np.array(
    [[1,2,3],
     [4,5,6]]
)

In [19]:
print(m)

[[1 2 3]
 [4 5 6]]


In [25]:
print(m.shape)
print(m.size)
print(m.ndim)

(2, 3)
6
2


In [30]:
t = np.array(
    [[[ 1,2,3,],
      [ 4,5,6 ]],
     [[ 7,8,9 ],
      [ 10,11,12]]
    ]
) 

t.shape

(2, 2, 3)

In [35]:
# create a numpy array by feeding the desired shape using the zeros()
z = np.zeros((2,2,3))
z

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
# create a numpy array by feeding the desired shape using the one()
o = np.ones((2,2,3))
o

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [48]:
# experimenting
e = np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
ra = np.random.uniform(5,10, (3,4))
##ra = np.random.randint(5,10, (3,4))

ra

array([[6.49141231, 7.63848795, 8.80351177, 9.15131001],
       [6.73471716, 8.16018606, 7.20469394, 8.2630587 ],
       [6.09547568, 9.93720348, 7.81280444, 5.07196351]])

In [57]:
r = np.arange(10,20,0.5)
#r

l = np.linspace(-10,10,20)
l

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [67]:
# why numpy is fast
np_x = np.random.rand(100_000_000)
list_x = list(np_x)

In [68]:
type(list_x)

list

In [73]:
result1 = np.zeros(np_x.shape)
for i, x in enumerate (np_x):
    result1[i] = x ** 3

In [74]:
result2 = []
for i, x in enumerate (list_x):
    result2.append(x ** 3)

In [76]:
result3 = np_x ** 3
result3

array([4.61551487e-01, 5.48732427e-02, 3.16248973e-01, ...,
       2.79922717e-02, 3.34893694e-04, 2.14361597e-01])